sudo: required
dist: trusty

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y curl make gcc-aarch64-linux-gnu qemu-system-arm
  - curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain nightly -y 
  - source ~/.cargo/env && rustup target add aarch64-unknown-linux-gnu
  - which qemu-system-aarch64
language: bash
script: source ~/.cargo/env && make rust && timeout 10 make qemu > output && cat output 
